// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiaepvGPOa0juEP5eMZu29dYe1LWzcsqE',
    appId: '1:71681103864:web:3086f2249409122e5ee80d',
    messagingSenderId: '71681103864',
    projectId: 'sweet-shop-e49ec',
    authDomain: 'sweet-shop-e49ec.firebaseapp.com',
    storageBucket: 'sweet-shop-e49ec.appspot.com',
    measurementId: 'G-T4S0Q7JFMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt2wnE6a4-KLexrqCcdZJ3gPa2O3ccY_g',
    appId: '1:71681103864:android:2dc696aaf9af68185ee80d',
    messagingSenderId: '71681103864',
    projectId: 'sweet-shop-e49ec',
    storageBucket: 'sweet-shop-e49ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSiEiKnLUWTZR4J2oROfAwT9VCUAGo_WM',
    appId: '1:71681103864:ios:cecc0f1396a8d8245ee80d',
    messagingSenderId: '71681103864',
    projectId: 'sweet-shop-e49ec',
    storageBucket: 'sweet-shop-e49ec.appspot.com',
    iosBundleId: 'com.example.sweetShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSiEiKnLUWTZR4J2oROfAwT9VCUAGo_WM',
    appId: '1:71681103864:ios:cecc0f1396a8d8245ee80d',
    messagingSenderId: '71681103864',
    projectId: 'sweet-shop-e49ec',
    storageBucket: 'sweet-shop-e49ec.appspot.com',
    iosBundleId: 'com.example.sweetShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiaepvGPOa0juEP5eMZu29dYe1LWzcsqE',
    appId: '1:71681103864:web:a330b3f63e04ace75ee80d',
    messagingSenderId: '71681103864',
    projectId: 'sweet-shop-e49ec',
    authDomain: 'sweet-shop-e49ec.firebaseapp.com',
    storageBucket: 'sweet-shop-e49ec.appspot.com',
    measurementId: 'G-HXKK0038Y7',
  );
}
